title: Group 12 - Turtle Up
email: nguyenm8@udayton.edu
description: Capstone project for CPS 491 at the University of Dayton
author: Michael Nguyen
baseurl: ""
url: "https://https://nguyenm8.github.io/group-12-website-jekyll/"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
